---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:lts-alpine
    commands:
      - npm install
      - npm run build

  - name: bake-stable
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: rubasace/rsocket-chat-client-js
      tags: stable
    when:
      branch:
        - master

  - name: bake-beta
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      repo: rubasace/rsocket-chat-client-js
      tags: beta
    when:
      branch:
        - release/*

---
kind: signature
hmac: 634c304df16ef93fe256b1d972d372682b4e711e7194cbc2944493353fb98009

...
